const $=id=>document.getElementById(id), euro=n=>Number(n||0).toLocaleString('fr-FR',{style:'currency',currency:'EUR'}), today=()=>new Date().toISOString().slice(0,10), nowTime=()=>new Date().toTimeString().slice(0,5), uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const feet=[['PAvG','Antérieur gauche'],['PAvD','Antérieur droit'],['PArG','Postérieur gauche'],['PArD','Postérieur droit']];
const issues=['Cerise','Abcès','Dermatite','Ulcère de sole','Ligne blanche','Fourchet','Limace','Seime','Double sole','Hémorragie','Décollement','Autre'];
const care=['Parage','Pansement','Talonnette','Désinfection','À surveiller','À revoir'];
const races=['abondance','angus','aubrac','autre','bazadaise','blonde','charolaise','gasconne','jersiaise','limousine','montbéliarde','prim holstein','salers','simmental','wagyu'];
let clients=[], jobs=JSON.parse(localStorage.getItem('parage.jobs')||'[]'), current=null;
let settings=Object.assign({vat:20,defaultFee:60,pairOne:20,pairMany:15,footOne:10,footMany:7.5,bandagePrice:5,blockPrice:15,businessName:'',businessDetails:''},JSON.parse(localStorage.getItem('parage.settings')||'{}'));
let costs=JSON.parse(localStorage.getItem('parage.costs')||'{}');
function saveAll(){localStorage.setItem('parage.jobs',JSON.stringify(jobs));}
function toast(m){$('toast').textContent=m;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='history')renderHistory();if(v==='exports')renderExports();if(v==='stats')renderStats();if(v==='home')renderHome();}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));
async function init(){try{clients=await fetch('clients.json').then(r=>r.json())}catch(e){clients=[]} $('races').innerHTML=races.map(x=>`<option value="${x}">`).join(''); bindClient(); loadSettings(); $('statsMonth').value=today().slice(0,7); renderHome(); newJob(); if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');}
function bindClient(){let t; $('cheptel').addEventListener('input',e=>{clearTimeout(t);let q=e.target.value.replace(/\D/g,'');t=setTimeout(()=>{let c=clients.find(x=>x.cheptel===q);if(c){$('clientName').value=c.nom;$('address').value=c.adresse;$('cpVille').value=c.cpVille;$('department').value=c.departement;renderPaymentAlert()}},120)});}
function blankJob(){return{id:uid(),cheptel:'',clientName:'',address:'',cpVille:'',department:'',race:'',date:today(),start:nowTime(),end:'',bull:'non',fee:settings.defaultFee,adjustment:0,comment:'',animals:[],status:'draft',exportedAt:null,paymentStatus:'',invoiceNo:'',createdAt:new Date().toISOString()}}
function newJob(){current=blankJob();fillJob();}
function fillJob(){[['cheptel','cheptel'],['clientName','clientName'],['address','address'],['cpVille','cpVille'],['department','department'],['race','race'],['jobDate','date'],['startTime','start'],['endTime','end'],['bull','bull'],['fee','fee'],['adjustment','adjustment'],['jobComment','comment']].forEach(([id,k])=>$(id).value=current[k]??'');renderAnimals();renderTotals();renderPaymentAlert();}
function syncJob(){[['cheptel','cheptel'],['clientName','clientName'],['address','address'],['cpVille','cpVille'],['department','department'],['race','race'],['jobDate','date'],['startTime','start'],['endTime','end'],['bull','bull'],['fee','fee'],['adjustment','adjustment'],['jobComment','comment']].forEach(([id,k])=>current[k]=$(id).value);current.fee=+current.fee||0;current.adjustment=+current.adjustment||0;}
['fee','adjustment'].forEach(id=>document.addEventListener('input',e=>{if(e.target.id===id){syncJob();renderTotals()}}));
function addAnimal(){current.animals.forEach(a=>a.collapsed=true);let a={id:uid(),number:'',category:'V',notes:'',checkNext:false,claws:{},workedFeet:[],collapsed:false};current.animals.push(a);renderAnimals();setTimeout(()=>document.querySelector(`[data-animal-number="${a.id}"]`)?.focus(),30);}
function completeAnimal(id){let a=current.animals.find(x=>x.id===id);if(!a)return;if(!String(a.number||'').trim())return toast('Saisissez le numéro de travail');a.collapsed=true;saveDraftSilently();addAnimal();toast('Bovin enregistré — saisissez le suivant')}
function toggleAnimal(id){let a=current.animals.find(x=>x.id===id);if(a){a.collapsed=!a.collapsed;renderAnimals()}}
function saveDraftSilently(){syncJob();let i=jobs.findIndex(x=>x.id===current.id);if(i<0)jobs.push(JSON.parse(JSON.stringify(current)));else jobs[i]=JSON.parse(JSON.stringify(current));saveAll()}
function ensureWorkedFeet(a){if(!Array.isArray(a.workedFeet))a.workedFeet=[];for(let code of feet.map(f=>f[0])){if(Object.entries(a.claws||{}).some(([k,d])=>k.startsWith(code+'-')&&d.touched)&&!a.workedFeet.includes(code))a.workedFeet.push(code)}}
function setWorkedFeet(id,codes,on=true){let a=current.animals.find(x=>x.id===id);if(!a)return;ensureWorkedFeet(a);codes.forEach(code=>{let i=a.workedFeet.indexOf(code);if(on&&i<0)a.workedFeet.push(code);if(!on&&i>=0)a.workedFeet.splice(i,1)});renderAnimals()}
function toggleFoot(id,code){let a=current.animals.find(x=>x.id===id);ensureWorkedFeet(a);setWorkedFeet(id,[code],!a.workedFeet.includes(code))}
function animalHistory(num){if(!num||!current.cheptel)return[];return jobs.filter(j=>j.cheptel===current.cheptel&&j.id!==current.id).flatMap(j=>j.animals.filter(a=>a.number===num).map(a=>({date:j.date,animal:a}))).sort((a,b)=>b.date.localeCompare(a.date));}
function renderAnimals(){$('animals').innerHTML=current.animals.length?'':'<p>Aucun bovin saisi.</p>';current.animals.forEach((a,i)=>{ensureWorkedFeet(a);let h=animalHistory(a.number), div=document.createElement('div');div.className='animal'+(a.collapsed?' collapsed':'');let doneSummary=`${a.workedFeet.length} pied(s) fait(s)${summaryAnimal(a)!=='aucun problème signalé'?' · '+summaryAnimal(a):''}`;div.innerHTML=`<div class="animalHead"><strong>Bovin ${i+1}${a.number?' — '+esc(a.number):''}</strong>${a.collapsed?`<span class="animalSummary">${esc(doneSummary)}</span><button onclick="toggleAnimal('${a.id}')">Modifier</button>`:`<input data-animal-number="${a.id}" inputmode="numeric" autocomplete="off" placeholder="N° de travail" value="${esc(a.number)}" oninput="updateAnimal('${a.id}','number',this.value)" onblur="refreshAnimal('${a.id}')" onkeydown="if(event.key==='Enter'){event.preventDefault();this.blur()}"><select onchange="updateAnimal('${a.id}','category',this.value)">${['V','Gén','JB','T','B'].map(x=>`<option ${a.category===x?'selected':''}>${x}</option>`).join('')}</select><label><input type="checkbox" ${a.checkNext?'checked':''} onchange="updateAnimal('${a.id}','checkNext',this.checked)"> À vérifier</label><button onclick="removeAnimal('${a.id}')">Supprimer</button>`}</div>${a.collapsed?'':`${h.length?`<div class="historyAlert"><b>Historique trouvé</b> — dernier passage ${fmtDate(h[0].date)} : ${summaryAnimal(h[0].animal)}</div>`:''}<div class="quickFeet"><b>Parage rapide :</b><button onclick="setWorkedFeet('${a.id}',['PAvG','PAvD'],true)">Antérieurs (1 paire)</button><button onclick="setWorkedFeet('${a.id}',['PArG','PArD'],true)">Postérieurs (1 paire)</button><button onclick="setWorkedFeet('${a.id}',['PAvG','PAvD','PArG','PArD'],true)">4 pieds (2 paires)</button><button onclick="setWorkedFeet('${a.id}',['PAvG','PAvD','PArG','PArD'],false)">Effacer les pieds</button></div><p class="hint">Cliquez sur « Pied fait » pour un pied seul. Cliquez sur un onglon uniquement pour enregistrer un problème ou un soin.</p><div class="feet">${feet.map(f=>footHTML(a,f[0],f[1])).join('')}</div><label>Observation générale<input value="${esc(a.notes)}" onchange="updateAnimal('${a.id}','notes',this.value)"></label><div class="animalActions"><button class="primary big" onclick="completeAnimal('${a.id}')">✓ Bovin terminé → suivant</button></div>`}`;$('animals').appendChild(div)});renderTotals();}
function refreshAnimal(id){let a=current.animals.find(x=>x.id===id);if(a&&!a.collapsed)renderAnimals()}
function footHTML(a,code,label){ensureWorkedFeet(a);let worked=a.workedFeet.includes(code);return `<div class="foot ${worked?'worked':''}"><h4>${label}</h4><button class="footDone ${worked?'on':''}" onclick="toggleFoot('${a.id}','${code}')">${worked?'✓ Pied fait':'Marquer le pied fait'}</button><div class="claws">${['Int','Ext'].map(o=>{let k=code+'-'+o,d=a.claws[k]||{}, cls=(d.issues?.length||d.care?.length)?'problem':'';return `<button class="claw ${cls}" onclick="editClaw('${a.id}','${k}')"><b>${o==='Int'?'Interne':'Externe'}</b><br><small>${[...(d.issues||[]),...(d.care||[])].slice(0,2).join(', ')||'Ajouter un problème'}</small></button>`}).join('')}</div></div>`}
function editClaw(aid,key){let a=current.animals.find(x=>x.id===aid),d=a.claws[key]||{touched:true,issues:[],care:[],note:''};let overlay=document.createElement('div');overlay.className='detailBox';overlay.style.position='fixed';overlay.style.inset='10% 5%';overlay.style.zIndex=20;overlay.style.overflow='auto';overlay.style.boxShadow='0 0 0 9999px #0008';overlay.innerHTML=`<div class="toolbar"><h3>${key}</h3><button id="closeDetail">Fermer</button></div><p class="hint">Le pied sera automatiquement marqué comme réalisé si vous enregistrez un problème ou un soin.</p><h4>Problèmes</h4><div class="chips">${issues.map(x=>`<button class="chip ${(d.issues||[]).includes(x)?'on':''}" data-type="issue" data-val="${x}">${x}</button>`).join('')}</div><h4>Soins</h4><div class="chips">${care.map(x=>`<button class="chip ${(d.care||[]).includes(x)?'on':''}" data-type="care" data-val="${x}">${x}</button>`).join('')}</div><label>Commentaire<input id="clawNote" value="${esc(d.note||'')}"></label><div class="actions"><button id="clearDetail">Effacer</button><button class="primary" id="saveDetail">Enregistrer</button></div>`;document.body.appendChild(overlay);overlay.querySelectorAll('.chip').forEach(b=>b.onclick=()=>b.classList.toggle('on'));overlay.querySelector('#closeDetail').onclick=()=>overlay.remove();overlay.querySelector('#clearDetail').onclick=()=>{delete a.claws[key];overlay.remove();renderAnimals()};overlay.querySelector('#saveDetail').onclick=()=>{a.claws[key]={touched:true,issues:[...overlay.querySelectorAll('[data-type=issue].on')].map(x=>x.dataset.val),care:[...overlay.querySelectorAll('[data-type=care].on')].map(x=>x.dataset.val),note:overlay.querySelector('#clawNote').value};if(a.claws[key].care.includes('À revoir'))a.checkNext=true;let footCode=key.split('-')[0];ensureWorkedFeet(a);if(!a.workedFeet.includes(footCode))a.workedFeet.push(footCode);overlay.remove();renderAnimals()};}
function updateAnimal(id,k,v){let a=current.animals.find(x=>x.id===id);if(!a)return;a[k]=v;renderTotals()}
function removeAnimal(id){current.animals=current.animals.filter(x=>x.id!==id);renderAnimals()}
function calc(j=current){let n=j.animals.filter(a=>String(a.number||'').trim()||Object.keys(a.claws||{}).length||(a.workedFeet||[]).length).length,pairs=0,single=0,band=0,blocks=0;for(let a of j.animals){ensureWorkedFeet(a);let worked=a.workedFeet.length;pairs+=Math.floor(worked/2);single+=worked%2;for(let d of Object.values(a.claws)){if((d.care||[]).includes('Pansement'))band++;if((d.care||[]).includes('Talonnette'))blocks++;}}let pairRate=n===1?settings.pairOne:settings.pairMany,footRate=n===1?settings.footOne:settings.footMany;let careTotal=pairs*pairRate+single*footRate+band*settings.bandagePrice+blocks*settings.blockPrice;let ht=(+j.fee||0)+careTotal+(+j.adjustment||0),ttc=ht*(1+settings.vat/100);return{n,pairs,single,band,blocks,careTotal,ht,ttc,pairRate,footRate}}
function renderTotals(){let c=calc();$('jobTotals').innerHTML=`<span>Animaux <b>${c.n}</b></span><span>Paires <b>${c.pairs}</b></span><span>Pieds seuls <b>${c.single}</b></span><span>Pansements <b>${c.band}</b></span><span>Talonnettes <b>${c.blocks}</b></span><span>Total HT <b>${euro(c.ht)}</b></span><span>TTC <b>${euro(c.ttc)}</b></span>`}
function saveJob(){syncJob();if(!current.cheptel)return toast('Saisissez le numéro de cheptel');let i=jobs.findIndex(x=>x.id===current.id);if(i<0)jobs.push(current);else jobs[i]=current;saveAll();toast('Chantier enregistré');renderHome()}
function finishJob(){current.animals=current.animals.filter(a=>String(a.number||'').trim()||Object.keys(a.claws||{}).length||(a.workedFeet||[]).length);syncJob();if(!current.end)current.end=nowTime();current.status='finished';saveJob();fillJob();toast('Chantier terminé et prêt à transmettre')}
function renderPaymentAlert(){let unpaid=jobs.filter(j=>j.cheptel===current.cheptel&&['pending','late','partial'].includes(j.paymentStatus));$('paymentAlert').innerHTML=unpaid.length?`<div class="alertRed"><b>Alerte paiement :</b> ${unpaid.length} facture(s) en attente pour cet élevage, total ${euro(unpaid.reduce((s,j)=>s+calc(j).ttc,0))}.</div>`:''}
function summaryAnimal(a){let arr=[];for(let [k,d] of Object.entries(a.claws||{})){if(d.issues?.length||d.care?.length)arr.push(`${k}: ${[...(d.issues||[]),...(d.care||[])].join(', ')}`)}return arr.join(' ; ')||'aucun problème signalé'}
function renderHome(){let month=today().slice(0,7),m=jobs.filter(j=>j.date?.startsWith(month)),c=m.reduce((s,j)=>{let x=calc(j);Object.keys(x).forEach(k=>typeof x[k]==='number'&&(s[k]=(s[k]||0)+x[k]));return s},{});$('homeCards').innerHTML=card('Chantiers du mois',m.length)+card('Bovins',c.n||0)+card('Pieds travaillés',(c.pairs||0)*2+(c.single||0))+card('À transmettre',jobs.filter(j=>j.status==='finished'&&!j.exportedAt).length)}
function card(t,v){return `<div class="card"><span>${t}</span><b>${v}</b></div>`}
function renderHistory(){let q=($('historySearch').value||'').toLowerCase(),arr=jobs.filter(j=>[j.cheptel,j.clientName,...j.animals.map(a=>a.number)].join(' ').toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date));$('historyList').innerHTML=arr.map(j=>{let c=calc(j);return `<div class="row"><div class="grow"><b>${fmtDate(j.date)} — ${esc(j.clientName||j.cheptel)}</b><br><small>${j.cheptel} · ${c.n} bovin(s) · ${c.pairs} paire(s) · ${c.band} pansement(s)</small></div><span class="status ${j.exportedAt?'sent':'pending'}">${j.exportedAt?'Transmis':j.status==='finished'?'À transmettre':'Brouillon'}</span><button onclick="openJob('${j.id}')">Ouvrir</button></div>`}).join('')||'<p>Aucun chantier.</p>'}
function openJob(id){current=JSON.parse(JSON.stringify(jobs.find(x=>x.id===id)));fillJob();showView('chantier')}
function renderExports(){let arr=jobs.filter(j=>j.status==='finished'&&!j.exportedAt);$('exportList').innerHTML=arr.map(j=>`<div class="row"><input type="checkbox" class="expCheck" value="${j.id}"><div class="grow"><b>${fmtDate(j.date)} — ${esc(j.clientName||j.cheptel)}</b><br><small>${j.cheptel} · ${calc(j).n} bovins · ${euro(calc(j).ttc)} TTC</small></div></div>`).join('')||'<p>Aucun chantier à transmettre.</p>'}
function selectAllExports(){document.querySelectorAll('.expCheck').forEach(x=>x.checked=true)}
function exportAccounting(){let ids=[...document.querySelectorAll('.expCheck:checked')].map(x=>x.value);if(!ids.length)return toast('Sélectionnez au moins un chantier');let rows=jobs.filter(j=>ids.includes(j.id)), headers=['mois intervention','Date','Cheptel','Nom PRENOM','Adresse','CP + VILLE','Race','taureau fait  ?','DEPARTEMENT','FORFAIT + MISE EN PLACE','NBR Animaux totaux','NBR DE PAIRE','PIED à l\'unité','NBR DE PANSEMENT','NBR DE TALONNETTE','MONTANT SOIN TOTAUX','PRIX HT','PRIX TTC','Commentaires','Devis','FACTURE LE','Réglé le','TYPE'];let xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="saisie"><Table>${xmlRow(headers)}`;for(let j of rows){let c=calc(j),month=j.date.slice(0,7)+'-01',comments=[j.comment,...j.animals.filter(a=>a.checkNext).map(a=>`À revoir ${a.number}`)].filter(Boolean).join(' | ');xml+=xmlRow([month,j.date,j.cheptel,j.clientName,j.address,j.cpVille,j.race,j.bull,j.department,j.fee,c.n,c.pairs,c.single,c.band,c.blocks,c.careTotal,c.ht,c.ttc,comments,j.date,'','',''])}xml+='</Table></Worksheet></Workbook>';download(new Blob([xml],{type:'application/vnd.ms-excel'}),`Export_parage_${today()}.xls`);rows.forEach(j=>j.exportedAt=new Date().toISOString());saveAll();renderExports();toast('Export comptable créé')}
function xmlRow(a){return '<Row>'+a.map(v=>`<Cell><Data ss:Type="${typeof v==='number'?'Number':'String'}">${xmlEsc(v??'')}</Data></Cell>`).join('')+'</Row>'}
function printProforma(){syncJob();let c=calc(), details=current.animals.flatMap(a=>Object.entries(a.claws).filter(([k,d])=>d.touched||d.issues?.length||d.care?.length).map(([k,d])=>`<tr><td>${esc(a.number)}</td><td>${esc(a.category)}</td><td>${k.split('-')[0]}</td><td>${k.split('-')[1]}</td><td>${esc((d.issues||[]).join(', '))}</td><td>${esc((d.care||[]).join(', '))}</td><td>${esc(d.note||'')}</td></tr>`)).join('');let w=open('','_blank');w.document.write(`<html><head><title>Pro forma ${current.cheptel}</title><style>body{font:14px Arial;margin:35px;color:#222}h1{color:#285c4d}table{width:100%;border-collapse:collapse;margin:15px 0}th,td{border:1px solid #aaa;padding:7px}th{background:#eef5f1}.right{text-align:right}.box{border:2px solid #285c4d;padding:12px}</style></head><body><h1>FACTURE PRO FORMA / COMPTE RENDU DE PARAGE</h1><p><b>${esc(settings.businessName)}</b><br>${nl2br(settings.businessDetails)}</p><div class="box"><b>Élevage :</b> ${esc(current.clientName)}<br><b>Cheptel :</b> ${esc(current.cheptel)}<br>${esc(current.address)} — ${esc(current.cpVille)}<br><b>Date :</b> ${fmtDate(current.date)} · ${current.start||''}–${current.end||''}</div><h2>Prestations</h2><table><tr><th>Prestation</th><th>Quantité</th><th>Tarif HT</th><th>Total HT</th></tr><tr><td>Déplacement et mise en place</td><td>1</td><td>${euro(current.fee)}</td><td>${euro(current.fee)}</td></tr><tr><td>Paires de pieds</td><td>${c.pairs}</td><td>${euro(c.pairRate)}</td><td>${euro(c.pairs*c.pairRate)}</td></tr><tr><td>Pieds à l'unité</td><td>${c.single}</td><td>${euro(c.footRate)}</td><td>${euro(c.single*c.footRate)}</td></tr><tr><td>Pansements</td><td>${c.band}</td><td>${euro(settings.bandagePrice)}</td><td>${euro(c.band*settings.bandagePrice)}</td></tr><tr><td>Talonnettes</td><td>${c.blocks}</td><td>${euro(settings.blockPrice)}</td><td>${euro(c.blocks*settings.blockPrice)}</td></tr>${current.adjustment?`<tr><td>Ajustement tarifaire</td><td>1</td><td>${euro(current.adjustment)}</td><td>${euro(current.adjustment)}</td></tr>`:''}<tr><th colspan="3" class="right">Total HT</th><th>${euro(c.ht)}</th></tr><tr><th colspan="3" class="right">TVA ${settings.vat}%</th><th>${euro(c.ttc-c.ht)}</th></tr><tr><th colspan="3" class="right">Total TTC</th><th>${euro(c.ttc)}</th></tr></table><h2>Récapitulatif de l'intervention</h2><p>${c.n} bovin(s), ${c.pairs} paire(s), ${c.single} pied(s) à l'unité, ${c.band} pansement(s), ${c.blocks} talonnette(s).</p><table><tr><th>N° bovin</th><th>Cat.</th><th>Pied</th><th>Onglon</th><th>Problème</th><th>Soin</th><th>Observation</th></tr>${details||'<tr><td colspan="7">Aucun problème particulier enregistré.</td></tr>'}</table><p><b>Commentaire :</b> ${esc(current.comment||'')}</p><p><i>Document pro forma établi sur place. La facture définitive sera émise par la comptabilité.</i></p><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function renderStats(){let m=$('statsMonth').value||today().slice(0,7),arr=jobs.filter(j=>j.date?.startsWith(m)),sum={n:0,pairs:0,single:0,band:0,blocks:0,ht:0,ttc:0};arr.forEach(j=>{let c=calc(j);Object.keys(sum).forEach(k=>sum[k]+=c[k]||0)});let co=costs[m]||{},costTotal=['fuel','toll','material','meals','other'].reduce((s,k)=>s+(+co[k]||0),0);$('statsCards').innerHTML=card('Interventions',arr.length)+card('Bovins',sum.n)+card('Pieds faits',sum.pairs*2+sum.single)+card('Pansements',sum.band)+card('Talonnettes',sum.blocks)+card('CA HT',euro(sum.ht))+card('Frais',euro(costTotal))+card('Résultat simplifié',euro(sum.ht-costTotal));[['costFuel','fuel'],['costToll','toll'],['costMaterial','material'],['costMeals','meals'],['costOther','other'],['costComment','comment']].forEach(([id,k])=>$(id).value=co[k]||'');let deps={},rs={};arr.forEach(j=>{deps[j.department||'Non renseigné']=(deps[j.department||'Non renseigné']||0)+1;rs[j.race||'Non renseignée']=(rs[j.race||'Non renseignée']||0)+calc(j).n});$('statsTables').innerHTML=`<div class="panel"><h3>Interventions par département</h3>${objTable(deps,'Département','Interventions')}</div><div class="panel"><h3>Bovins par race</h3>${objTable(rs,'Race','Bovins')}</div>`}
function objTable(o,a,b){return `<table><tr><th>${a}</th><th>${b}</th></tr>${Object.entries(o).sort((x,y)=>y[1]-x[1]).map(x=>`<tr><td>${esc(x[0])}</td><td>${x[1]}</td></tr>`).join('')}</table>`}
function saveCosts(){let m=$('statsMonth').value;costs[m]={fuel:+$('costFuel').value||0,toll:+$('costToll').value||0,material:+$('costMaterial').value||0,meals:+$('costMeals').value||0,other:+$('costOther').value||0,comment:$('costComment').value};localStorage.setItem('parage.costs',JSON.stringify(costs));renderStats();toast('Frais enregistrés')}
function loadSettings(){Object.keys(settings).forEach(k=>{let e=$(k);if(e)e.value=settings[k]});}
function saveSettings(){Object.keys(settings).forEach(k=>{let e=$(k);if(e)settings[k]=e.type==='number'?+e.value:e.value});localStorage.setItem('parage.settings',JSON.stringify(settings));toast('Paramètres enregistrés')}
function backupData(){download(new Blob([JSON.stringify({jobs,settings,costs},null,2)],{type:'application/json'}),`Sauvegarde_parage_${today()}.json`)}
function restoreData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);jobs=x.jobs||[];settings=Object.assign(settings,x.settings||{});costs=x.costs||{};saveAll();localStorage.setItem('parage.settings',JSON.stringify(settings));localStorage.setItem('parage.costs',JSON.stringify(costs));loadSettings();renderHome();toast('Sauvegarde restaurée')}catch{toast('Fichier invalide')}};r.readAsText(f)}
function download(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function fmtDate(d){if(!d)return'';return d.split('-').reverse().join('/')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function xmlEsc(s){return esc(s)}function nl2br(s){return esc(s).replace(/\n/g,'<br>')}
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('installBtn').hidden=true}};
init();
